### PR TITLE
Attempting to apply a Create React App structure to run this locally

### PR DESCRIPTION
**Pull request by japickering**

### CODE REVIEW

**Comment by mastir** [comment]
just install via [npm](https://www.npmjs.com/package/@mastir/react-diagram)

```
npx create-react-app my-app
cd my-app
npm i --save @mastir/react-diagram
npm start
```

**Comment by japickering** [comment]
Thanks, that worked. I'm not a fan of CSS injection by provider wrappers and static inline styles though. Can you make a branch that supports Tailwind CSS instead?

**Comment by japickering** [comment]
Here's my forked repo that makes your sandbox demo compatible with VS Code and Create React App:
https://github.com/japickering/create-diagram

**Comment by mastir** [comment]
Thanks for your interest. I am not familiar with Tailwind, but you can make one by coping [Tailwind sandbox](https://codesandbox.io/s/cra-tailwind-template-bp9ou), add `@mastir/react-diagram` as dependancy, copy demo code and replace mui components with tailwind ones

**Pull request closed without merging**
